# Akıllı Kariyer Asistanı - Yapılandırma Dosyası
# Bu dosya projenin ana ayarlarını içerir

# Genel iş arama ayarları
job_search_settings:
  target_sites: ["linkedin", "indeed"]  # Hangi sitelerde arama yapılacak
  default_hours_old: 72  # Varsayılan olarak son kaç saatteki ilanlar (JobSpy native)
  default_results_per_site: 25  # Her persona ve site için kaç sonuç çekilecek
  min_similarity_threshold: 60  # Benzerlik eşiği (%) - JobSpy ile daha kaliteli veri

# Persona bazlı arama konfigürasyonları
# Indeed'e göre optimize edilmiş ve negatif filtreli arama terimleri
persona_search_configs:
  Software_Engineer:
    term: "(\"Software Engineer\" OR \"Yazılım Mühendisi\") -Senior -Lead -Principal -Manager -Direktör"
    hours_old: 72
    results: 25

  Business_Analyst:
    term: "(\"Business Analyst\" OR \"İş Analisti\") (ERP OR SAP OR Process OR Süreç) -Senior -Lead -Manager"
    hours_old: 72
    results: 25

  Data_Analyst:
    term: "(\"Data Analyst\" OR \"Veri Analisti\" OR \"BI Analyst\" OR \"Business Intelligence\") (SQL OR Python OR PowerBI OR Tableau) -Senior -Lead"
    hours_old: 168
    results: 25

# Dosya yolları
paths:
  data_dir: "data"
  cv_file: "data/cv.txt"
  chromadb_dir: "data/chromadb"
  logs_dir: "logs"

# Embedding ayarları
embedding_settings:
  batch_size: 10
  retry_count: 3
  rate_limit_delay: 0.1  # saniye

# Vector store ayarları
vector_store_settings:
  collection_name: "job_embeddings"
  similarity_metric: "cosine"
  top_k_results: 50

# Intelligent scoring system configuration
scoring_system:
  weights:
    negative: -30
    positive: 30
  title_keywords:
    negative:
      - senior
      - "sr."
      - kıdemli
      - architect
      - director
      - manager
      - lead
    positive:
      - junior
      - entry
      - trainee
      - intern
      - stajyer
  description_weights:
    positive:
      "python,python3,py": 10
      "react,reactjs,react.js": 8
      "typescript,ts,javascript": 8
      "remote,uzaktan,home office,wfh": 15
      "agile,scrum,kanban": 5
      "api,rest,restful": 7
    negative:
      "müşteri ziyareti,saha": -15
      "yoğun seyahat": -20
      "satış hedefi,kota": -30
      "çağrı merkezi": -40
  experience_penalties:
    "10": -60
    "8": -50
    "5": -40
    "4": -20
    "3": -10
  cv_skill_keywords: []
  threshold: -20
  cv_skill_boost_threshold: 0.8
  cv_skill_bonus_points: 10
  dynamic_skill_weight: 10
  min_importance_for_scoring: 0.75
