[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "kariyer-asistani"
version = "1.0.0"
description = "Akıllı Kariyer Asistanı - AI tabanlı iş arama ve eşleştirme sistemi"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
    {name = "Furkan", email = "your-email@example.com"}
]
keywords = ["ai", "career", "job-search", "nlp", "machine-learning"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Office/Business :: Scheduling",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]

dependencies = [
    "python-jobspy>=1.1.80",
    "google-generativeai>=0.8.3",
    "chromadb>=1.0.12",
    "pandas>=2.2.2",
    "numpy>=1.26.3",
    "python-dotenv>=1.0.1",
    "PyYAML>=6.0.1",
    "tqdm>=4.66.1",
    "sentence-transformers>=3.0.1",
]

[project.optional-dependencies]
dev = [
    "black>=23.12.0",
    "flake8>=6.1.0",
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
]

[project.urls]
Homepage = "https://github.com/furkan-ucan/kariyer-asistani"
"Bug Reports" = "https://github.com/furkan-ucan/kariyer-asistani/issues"
"Source" = "https://github.com/furkan-ucan/kariyer-asistani"

[project.scripts]
kariyer-asistani = "main:main"

[tool.black]
line-length = 120
target-version = ['py38', 'py39', 'py310', 'py311', 'py312']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
  | kariyer-asistani-env
)/
'''

[tool.flake8]
max-line-length = 120
ignore = ["E203", "W503"]
exclude = [
    ".git",
    "__pycache__",
    "kariyer-asistani-env",
    ".venv",
    "build",
    "dist"
]
per-file-ignores = [
    "__init__.py:F401",
]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q --strict-markers"
testpaths = [
    "tests",
]
python_files = [
    "test_*.py",
    "*_test.py",
]
